services:
  sio_test:
    user: app
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    ports:
      - "8337:8337"
      - "9003:9003"
    volumes:
      - .:/app:rw
    environment:
      - APP_ENV=dev
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.orb.internal client_port=9003 start_with_request=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: